# pytorch basics

In [3]:
import torch

In [9]:
# tensor

# create a (3x3) tensor of random values between 0 and 1
x = torch.rand(3, 3)  
print(x)

# create a tensor filled with zeros or ones
zeros = torch.zeros(2, 2)
ones = torch.ones(2, 2)

# create tensors from Python lists
tensor_from_list = torch.tensor([[1, 2], [3, 4]])

# tensor attributes
print("Shape:", x.shape)  # Dimensions of the tensor
print("Data type:", x.dtype)  # Data type of tensor elements
print("Device:", x.device)  # Device (CPU or GPU) where the tensor resides

tensor([[0.6032, 0.3480, 0.1462],
        [0.7424, 0.0804, 0.2987],
        [0.4658, 0.3211, 0.5640]])
Shape: torch.Size([3, 3])
Data type: torch.float32
Device: cpu


In [27]:
# tensor operations

# element-wise addition
a = torch.tensor([2, 3])
b = torch.tensor([5, 6])
print(a + b)  # [7, 9, 11]

# element-wise multiplication
print(a * b)  # [10, 18, 28]

# matrix multiplication
c = torch.rand(2, 3)
d = torch.rand(3, 4)
print(torch.mm(c, d))  # Result is a (2x4) matrix

# reshaping tensors
x = torch.rand(3, 3)
x_reshaped = x.view(1, 9)  # Reshape to (1x9)
print(x_reshaped) # flattened tensor

tensor([7, 9])
tensor([10, 18])
tensor([[0.9055, 0.6976, 0.8879, 0.8953],
        [0.9036, 0.3908, 0.7551, 0.5087]])
tensor([[0.4532, 0.2530, 0.8634, 0.8838, 0.7986, 0.6280, 0.2144, 0.3975, 0.3244]])


In [72]:
# gradient tracking

# the function is y=f(x), how y changes with respect to x
# gradient is dy/dx
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3 
out = z.mean()

# Gradient of out
# out = z/4 = y*y*3/4 = (x+2)*(x+2)*3/4
# gradient = dy/dx = 3/4*(2x+4), set x=1, get gradient = 4.5
out.backward()
print(x.grad)

# use torch.no_grad() to disable gradient tracking
model = torch.nn.Linear(10, 1)
input_data = torch.randn(1, 10)
with torch.no_grad():
    output = model(input_data)
print("Model output:", output)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
Model output: tensor([[0.2039]])


In [78]:
# torch.nn, neural networks

# neural network layers
# fully connected (dense) layers
layer = torch.nn.Linear(1,1) # Linear layer with 1 input and 1 output
layer = torch.nn.Linear(10, 5) # Linear layer with 10 inputs and 5 outputs
print(layer.weight)  # Print weights of the layer

# dropout layer
layer = torch.nn.Dropout(p=0.5)  # Dropout with probability of 0.5
print(layer.forward(torch.randn(2, 2)))  # Apply dropout to a tensor  

# convolutional layers
layer = torch.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)  # 2D convolution
layer = torch.nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3)  # 1D convolution
print(layer.weight)  # Print weights of the convolutional layer

# pooling layers
layer = torch.nn.MaxPool2d(kernel_size=2)  # Max pooling

# recurrent layers
torch.nn.RNN(input_size=10, hidden_size=20)  # RNN layer
torch.nn.LSTM(input_size=10, hidden_size=20)  # LSTM layer
torch.nn.GRU(input_size=10, hidden_size=20)  # GRU layer

# activation functions
# softmax function
torch.nn.Softmax(dim=1) 

# sigmoid function
torch.nn.Sigmoid()

# relu function
torch.nn.ReLU()

# tanh function
torch.nn.Tanh()

# loss functions
# mean squared error loss
torch.nn.MSELoss()
# cross entropy loss
torch.nn.CrossEntropyLoss()
# binary cross entropy loss
torch.nn.BCELoss()

Parameter containing:
tensor([[-0.0370, -0.1446, -0.1152, -0.0570,  0.1380,  0.2700, -0.0251,  0.1950,
          0.0675, -0.2551],
        [-0.2163, -0.1290,  0.2934, -0.0519,  0.2082,  0.1411, -0.3083,  0.2654,
         -0.1328, -0.0178],
        [-0.3051, -0.0507, -0.1567, -0.0532, -0.1814,  0.1584,  0.1134,  0.2943,
         -0.2220,  0.2257],
        [ 0.0224,  0.0806,  0.1551,  0.1949, -0.2177, -0.1695,  0.2229, -0.0412,
         -0.2169,  0.2905],
        [-0.2569, -0.3022,  0.2152, -0.2706, -0.0049,  0.1240, -0.2220,  0.2481,
          0.0537,  0.2907]], requires_grad=True)
tensor([[-0.1168, -0.0000],
        [ 3.6211,  0.0000]])
Parameter containing:
tensor([[[-0.2871,  0.3725, -0.3341]]], requires_grad=True)


BCELoss()

In [ ]:
# optimizers