# pytorch basics

In [3]:
import torch

In [9]:
# tensor
# create a (3x3) tensor of random values between 0 and 1
x = torch.rand(3, 3)  
print(x)

# create a tensor filled with zeros or ones
zeros = torch.zeros(2, 2)
ones = torch.ones(2, 2)

# create tensors from Python lists
tensor_from_list = torch.tensor([[1, 2], [3, 4]])

# tensor attributes
print("Shape:", x.shape)  # Dimensions of the tensor
print("Data type:", x.dtype)  # Data type of tensor elements
print("Device:", x.device)  # Device (CPU or GPU) where the tensor resides

tensor([[0.6032, 0.3480, 0.1462],
        [0.7424, 0.0804, 0.2987],
        [0.4658, 0.3211, 0.5640]])
Shape: torch.Size([3, 3])
Data type: torch.float32
Device: cpu


In [27]:
# tensor operations
# element-wise addition
a = torch.tensor([2, 3])
b = torch.tensor([5, 6])
print(a + b)  # [7, 9, 11]

# element-wise multiplication
print(a * b)  # [10, 18, 28]

# matrix multiplication
c = torch.rand(2, 3)
d = torch.rand(3, 4)
print(torch.mm(c, d))  # Result is a (2x4) matrix

# reshaping tensors
x = torch.rand(3, 3)
x_reshaped = x.view(1, 9)  # Reshape to (1x9)
print(x_reshaped) # flattened tensor

tensor([7, 9])
tensor([10, 18])
tensor([[0.9055, 0.6976, 0.8879, 0.8953],
        [0.9036, 0.3908, 0.7551, 0.5087]])
tensor([[0.4532, 0.2530, 0.8634, 0.8838, 0.7986, 0.6280, 0.2144, 0.3975, 0.3244]])


In [2]:
# troch.zeros_like

input_tensor = torch.randn(2, 3, dtype=torch.float32)
output_tensor = torch.zeros_like(input_tensor)

print(f"Input Tensor:\n{input_tensor}")
print(f"Shape of Input Tensor: {input_tensor.size()}")
print(f"Data type of Input Tensor: {input_tensor.dtype}")
print(f"Output Tensor:\n{output_tensor}")
print(f"Shape of Output Tensor: {output_tensor.size()}")
print(f"Data type of Output Tensor: {output_tensor.dtype}")

Input Tensor:
tensor([[ 0.0865, -0.8413,  1.0471],
        [ 1.3969, -0.0030, -0.8434]])
Shape of Input Tensor: torch.Size([2, 3])
Data type of Input Tensor: torch.float32
Output Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape of Output Tensor: torch.Size([2, 3])
Data type of Output Tensor: torch.float32
